spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasks?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: '!QAZzaq1'
  jpa:
    hibernate:
      ddl-auto: update

someParameter:
  value: 5463